const {chromium}=require('/Users/bpham/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Users/bpham/Library/Caches/ms-playwright/chromium_headless_shell-1228/chrome-headless-shell-mac-arm64/chrome-headless-shell'});const page=await browser.newPage({reducedMotion:'reduce',viewport:{width:1000,height:1100}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{window.open=(url)=>{window.lastOpened=url;return null;};});await page.goto('http://127.0.0.1:4173');await page.waitForFunction(()=>__game.artReady);
for(const id of ['home','contact','mart']){await page.evaluate(id=>{__game.teleport(id);__game.press('up');},id);assert.equal(await page.evaluate(()=>__game.state),'room');await page.locator('#game').screenshot({path:`output/interior-${id}.png`});const objects=await page.evaluate(()=>__game.room.objects);
for(const object of objects){await page.evaluate(target=>{const r=__game.room,queue=[[r.x,r.y,[]]],seen=new Set();let found;const dirs=[[0,-1,'up'],[0,1,'down'],[-1,0,'left'],[1,0,'right']];for(let i=0;i<queue.length;i++){const[x,y,path]=queue[i];for(const[dx,dy,k]of dirs)if(x+dx===target.x&&y+dy===target.y){found=[...path,k];break;}if(found)break;for(const[dx,dy,k]of dirs){const nx=x+dx,ny=y+dy,key=nx+','+ny;if(nx<1||nx>13||ny<2||ny>8||seen.has(key)||r.objects.some(o=>o.x===nx&&o.y===ny))continue;seen.add(key);queue.push([nx,ny,[...path,k]]);}}if(!found)throw Error('Unreachable '+target.label);for(const k of found){__game.tick(8);__game.press(k);}__game.press('a');},object);
if(object.label==='SHOPKEEPER'){assert.equal(await page.evaluate(()=>__game.state),'menu');await page.evaluate(()=>__game.press('a'));assert.match(await page.evaluate(()=>__game.dialogue.text),/POTION/);}
else assert.equal(await page.evaluate(()=>__game.state),'dialog',object.label);
await page.evaluate(()=>{for(let i=0;i<150&&__game.state==='dialog';i++)__game.press('a');});if(object.label==='VIBE CODING'){assert.equal(await page.evaluate(()=>__game.state),'menu');await page.evaluate(()=>__game.press('a'));assert.equal(await page.evaluate(()=>window.lastOpened),'https://trainedonvibes.com');}else if(await page.evaluate(()=>__game.state)==='menu')await page.evaluate(()=>__game.press('b'));assert.equal(await page.evaluate(()=>__game.state),'room');}
await page.evaluate(()=>__game.press('b'));assert.equal(await page.evaluate(()=>__game.state),'world');}
assert.deepEqual(errors,[]);console.log('PASS: all 15 objects reachable, skill shop, room returns, exits, Trained on Vibes URL, no runtime errors');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
